Repository marklogic/marklogic-data-hub, pull requests merged in 2018-11, with the labels that each got.

#1492 DHFPROD-1479 - Fixed broken links.
  _data/sidenav.yml
  _pages/docs/release-notes.md
  _pages/faqs.md
  _pages/tutorial/2x/modeling-product-entity.md
  _pages/tutorial/2x/wrapping-up.md
  _pages/understanding/projectstructure.md
  _pages/understanding/understanding.md
  _pages/understanding/upgrading.md
  javadocs/2.0.4/overview-summary.html
Labels: Documentation

#1546 DHFPROD-1410 left-align input-flow buttons
  quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.html
  quick-start/src/main/ui/app/mlcp-ui/mlcp-ui.component.scss
Labels: Component:QuickStart

#1556 DHFPROD-1408 no save if uri/desc unchanged
  quick-start/src/main/ui/app/mappings/map.component.ts
Labels: Component:QuickStart

#1555 DHFPROD-1411 display new flow in view after save
  quick-start/src/main/ui/app/flows/flows.component.ts
Labels: Component:QuickStart

#1560 fix QuickStart type issue in getFlowType()
  quick-start/src/main/ui/app/flows/flows.component.ts
Labels: Component:QuickStart

#1604 DHFPROD-1426 hide QuickStart help icons
  quick-start/src/main/ui/app/entity-modeler/entity-box.component.html
  quick-start/src/main/ui/app/entity-modeler/entity-editor.component.html
  quick-start/src/main/ui/app/mappings/map.component.html
Labels: Component:QuickStart, Documentation
