Repository marklogic/marklogic-data-hub, pull requests merged in 2021-05, with the labels that each got.

#5585 DEVO-191:Update DHF develop pipeline to include HC on-prem
  Jenkinsfile
Labels: 5.4.4

#5611 DEVO-242: Run regressions and release 5.2.7
  marklogic-data-hub/build.gradle
Labels: 5.2.7

#5628 DEVO-240: Investigate connection issues in nightly regressions
  Jenkinsfile
Labels: 5.4.4

#5649 DEVO-240: Investigate connection issues in nightly regressions
  Jenkinsfile
Labels: 5.4.4

#5654 DHFPROD-7330: Explore All Data shows data when entity models are empty
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
Labels: 5.4.4

#5661 DHFPROD-7302: (5.4) Better messages for common write errors
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/suite-setup.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/test-data/entities/Customer.entity.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-utils/writeDocuments.sjs
Labels: 5.4.4

#5728 DEVO-281: Increase timeout in DHF regression pipeline
  Jenkinsfile
Labels: 5.4.5
