Repository marklogic/marklogic-data-hub, pull requests merged in 2022-03, with the labels that each got.

#6560 DHFPROD-8529: graphSearch Failure on Nightly
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
Labels: DO_NOT_RUN_UI_TESTS

#6561 DHFPROD-8495: Don't extract entity info as part of match/merge
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/util.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/utils/suite-setup.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/utils/test-data/entities/TestTitle.entity.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/utils/titleExtractionTest.sjs
Labels: DO_NOT_RUN_UI_TESTS

#6568 DHFPROD-8437: FixCreatedByStepTest Core Failure
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java
Labels: DO_NOT_RUN_UI_TESTS

#6567 DHFPROD-8497: Incorporate filterQuery in match preview
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/content/CustMatchMergeExcludedByFilter.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/previewMatchingActivity/test-data/steps/matching/matchCustomers.step.json
Labels: DO_NOT_RUN_UI_TESTS

#6572 DHFPROD-8521: Re Add Run Flows From Run Tile
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/pages/Run.test.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/theme/HCVariables.scss
Labels: 5.7.1

#6593 DHFPROD-8593: Pagination not working in Table and Snippet views in explore
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
Labels: 5.7.1

#6563 DHFPROD-7934: Navigate to Graph Settings
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.module.scss
  marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
  marklogic-data-hub-central/ui/src/components/tiles/tiles.module.scss
  marklogic-data-hub-central/ui/src/components/tiles/tiles.test.tsx
  marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
  marklogic-data-hub-central/ui/src/config/explore.config.tsx
  marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js
  marklogic-data-hub-central/ui/src/config/themes.config.js
Labels: 5.8

#6603 DHFPROD-8191: e2e Failures on Windows nightly pt. 2
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/entityMappingMoreLessFunctionality.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyDataInDatabases.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
  marklogic-data-hub-central/ui/e2e/cypress/support/components/common/tiles.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/mapping/mapping-step-detail.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
Labels: 5.7.1

#6606 DHFPROD-8437: FixCreatedByStepTest Core Failure
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java
Labels: DO_NOT_RUN_UI_TESTS

#6614 DHFPROD-8644: Wait for indexes before running flow tests
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/flows/suite-setup.xqy
Labels: 5.7.1

#6585 DHFPROD-8541: Re-Add Run Flows Success and Error Messages
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addCustomStepToFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMatchStepToFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/customIngestion.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionCardView.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/pages/Run.test.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
Labels: 5.7.1

#6624 DHFPROD-8595: Incorrect Active Tab in Record XML/JSON View
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
  marklogic-data-hub-central/ui/src/pages/Detail.tsx
Labels: 5.7.1

#6616 DHFPROD-8596: Pagination not working as expected when changing entities in Explore
  marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
  marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub-central/ui/src/config/explore.config.tsx
  marklogic-data-hub-central/ui/src/util/search-context.tsx
Labels: 5.7.1

#6634 DHFPROD-8280: Default Strategy Tooltip
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-rule-modal.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/merge-strategy-modal.tsx
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.module.scss
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Labels: 5.7.1

#6643 DHFPROD-8669: Crear user data is not working when used by gradle command
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
Labels: DO_NOT_RUN_UI_TESTS

#6632 DHFPROD-8575: Allow separate transactions in custom steps
  marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepRunnerService.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/QueryStepRunner.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepRunner/processBatch.api
  marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/QueryStepRunnerTest.java
  marklogic-data-hub/src/test/resources/step-runner-transactions-test/data/runThroughTransactions.json
  marklogic-data-hub/src/test/resources/step-runner-transactions-test/flows/testFlow.flow.json
  marklogic-data-hub/src/test/resources/step-runner-transactions-test/src/main/ml-modules/root/custom-modules/custom/testTransactionsStep/main.sjs
  marklogic-data-hub/src/test/resources/step-runner-transactions-test/step-definitions/custom/testTransactionsStep/testTransactionsStep.step.json
  marklogic-data-hub/src/test/resources/step-runner-transactions-test/steps/custom/testTransactionsStep.step.json
Labels: DO_NOT_RUN_UI_TESTS

#6640 DHFPROD-8527: Parse XML options in hubFlowRunner
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java
Labels: DO_NOT_RUN_UI_TESTS

#6641 DHFPROD-8527: Parse XML options in hubFlowRunner
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/connected/IngestAndMapWithConnectedStepsTest.java
Labels: DO_NOT_RUN_UI_TESTS, 5.7.1

#6644 DHFPROD-7255: Update flow status modal every few seconds
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
Labels: 5.7.1

#6629 DHFPROD-8553: Save queries for multiple entities in explore
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreColumnSelector.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/queryWithMoreThanOneEntity.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
  marklogic-data-hub-central/ui/src/components/column-selector/column-selector.tsx
  marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
  marklogic-data-hub-central/ui/src/components/queries/queries.tsx
  marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.tsx
  marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/saveSavedQuery.sjs
Labels: 5.7.1

#6623 DHFPROD-8565: Error upon navigation to explore from Run tile
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/src/components/modal-status/modal-status.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/util/search-context.tsx
Labels: 5.7.1

#6626 DHFPROD-8569: Related entity icons still visible in the new entity icons sidebar, for table/snippet view
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.module.scss
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
Labels: 5.7.1

#6652 DHFPROD-7126: Ability to navigate to the output records of a step run
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/Constants.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/StepRangeFacetHandler.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/impl/StepRangeFacetHandlerTest.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/step/impl/WriteStepRunner.java
  marklogic-data-hub/src/main/resources/hub-internal-config/database-fields/staging-database.xml
  marklogic-data-hub/src/main/resources/ml-config/database-fields/final-database.xml
  marklogic-data-hub/src/main/resources/ml-modules-final/options/default.xml
  marklogic-data-hub/src/main/resources/ml-modules-staging/options/default.xml
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/consts.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
  ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/UpdateIndexesTaskTest.groovy
Labels: 5.7.1

#6600 DHFPROD-7187: Change Flow Run Settings In Run Tile
  marklogic-data-hub-central/ui/e2e/cypress/fixtures/input/person.xml
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
Labels: 5.7.1

#6657 DHFPROD-8528: Fix PROV-O code with JobID specified by hubFlowRunner XML
  marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java
  marklogic-data-hub/src/test/resources/test-projects/simple-custom-step/flows/simpleCustomStepFlow.flow.json
Labels: DO_NOT_RUN_UI_TESTS, 5.7.1

#6665 DHFPROD-8622: Related Entities Panel Fix
  marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.module.scss
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Labels: 5.7.1

#6649 DHFPROD-8439: Fix HC initial run of steps IDs that don't end with ste…
  marklogic-data-hub-central/ui/src/util/stomp.ts
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/flow-lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/flows/flowWithStepDetails.flow.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job2.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job3.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job4.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job5.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/steps/custom/customStep.step.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowWithLatestJobInfo.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowsWithStepDetails.sjs
  marklogic-data-hub/src/test/resources/test-projects/provenance-test/steps/mapping/map-customer.step.json
Labels: DO_NOT_RUN_UI_TESTS

#6648 DHFPROD-8439: Fix HC initial run of steps IDs that don't end with ste…
  marklogic-data-hub-central/ui/src/util/stomp.ts
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/flow/flow-lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/step/saveStep.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/flows/flowWithStepDetails.flow.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job2.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job3.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job4.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/jobs/job5.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/test-data/steps/custom/customStep.step.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowWithLatestJobInfo.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/flow/testGetFlowsWithStepDetails.sjs
  marklogic-data-hub/src/test/resources/test-projects/provenance-test/steps/mapping/map-customer.step.json
Labels: DO_NOT_RUN_UI_TESTS, 5.7.1

#6673 DHFPROD-8187: Pull changes from HC when exporting project
  ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ExportProjectTask.groovy
  ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ExportProjectTaskTest.groovy
Labels: DO_NOT_RUN_UI_TESTS

#6674 DHFPROD-8187: Pull changes from HC when exporting project
  ml-data-hub-plugin/src/main/groovy/com/marklogic/gradle/task/ExportProjectTask.groovy
  ml-data-hub-plugin/src/test/groovy/com/marklogic/gradle/task/ExportProjectTaskTest.groovy
Labels: DO_NOT_RUN_UI_TESTS
