Repository marklogic/marklogic-data-hub, pull requests merged in 2022-11, with the labels that each got.

#7329 DHFPROD-9646: Fixing clicking on explore graph logic for e2e.
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphCenterNode.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphConceptsSettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphEntitiesSettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
Labels: Needs E2E review

#7321 DHFPROD-9614: Disable Concept Actions Based on ML Version
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.module.scss
  marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
  marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getVersions.sjs
Labels: priority:high

#7341 DHFPROD-9660: Improving tests for graphSearchFacets.
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
Labels: priority:high, DO_NOT_RUN_UI_TESTS

#7338 DHFPROD-9581: In Modeling tile, properties that are structured are not shown correctly
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/concepts/TestConcept.concept.json
Labels: priority:high

#7339 DHFPROD-9654: refresh details information
  marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.tsx
Labels: priority:high

#7340 DHFPROD-9658: Matching two URI's after a wrong match is unresponsive
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreGraphFacetConsistentNavigation.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.module.scss
  marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/config/explorer-tooltips.config.js
Labels: priority:high

#7343 DHFPROD-9657: Limit number of nodes returned on graph search
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: priority:high, DO_NOT_RUN_UI_TESTS

#7326 DHFPROD-9050: Additional matching performance updates
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/DeployHubAmpsCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONObject.java
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/algorithms/thesaurus.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/impl/sm-es-impl.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/options-impl.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/matching.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/endpoints/collectorLib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/preview-matching-activity-lib.xqy
  marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/endpoints/collectorLib/prepareSourceQuery.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableXQueryTest.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/compile-options/mergeOptions.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMatches.sjs
Labels: priority:high

#7347 DHFPROD-9662: Disable Structured properties as a foreign key on the graph
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
Labels: priority:high

#7348 DHFPROD-9660: Fix e2e test pipeline graphSearchFacets
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
Labels: priority:high

#7349 DHFPROD-9664: BE - Missing DocURi in related elements after a search
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: priority:high

#7351 DHFPROD-9667: Address missing concepts in graph endpoint
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: priority:high

#7352 DHFPROD-9668: Fix for Arbitrary Code execution security vulnerability
  marklogic-data-hub-central/ui/package-lock.json
Labels: priority:high

#7345 DHFPROD-9663: Fix E2E tests on 11.0-Nightly-linux-On-Prem
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithInterceptorsAndCustomHook.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphFocusDefocusCluster.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/index.js
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
Labels: priority:high

#7358 DHFPROD-9611: hc-input fixes
  marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
Labels: 5.8

#7365 DHFPROD-9595: AddMonitorRunStatusE2e
  marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
Labels: 5.8.1

#7361 DHFPROD-8410: Remove unneeded tooltips for Explorer facet values
  marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet-element.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet-name.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Labels: 5.8.1

#7366 DHFPROD-9609: Clean up Console Warnings - Mapping Step Details
  marklogic-data-hub-central/ui/src/components/common/dropdown-with-search/dropdownWithSearch.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
Labels: 5.8.1

#7367 DHFPROD-9263: Clean up Console Warnings - Explore
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx
  marklogic-data-hub-central/ui/src/pages/Detail.tsx
Labels: 5.8.1

#7370 DHFPROD-9559: Notifications Table to use Record Labels when available
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/getNotifications.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/setup.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/customer1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/customer2.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/notification1.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/rest/mlSmNotifications/test-data/content/notification2.xml
Labels: 5.8.1

#7363 DHFPROD-9275: Enhancement on input search in explore page
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.module.scss
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.test.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Labels: 5.8.1

#7376 DHFPROD-9265: CleanUpConsoleWarningsModel
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Labels: 5.8.1

#7372 DHFPROD-9259: Clean up Console Warnings - Notifications
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
Labels: 5.8.1

#7396 DHFPROD-9705: Fix cypress tests to fail the test on failure
  marklogic-data-hub-central/ui/e2e/cypress/support/index.js
Labels: 5.8.1

#7400 DHFPROD-9706: Cannot check facets
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet-name.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Labels: 5.8.1

#7414 DHFPROD-9719: Fix intermittent failures on PRs
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSidePanel.spec.tsx
Labels: 5.8.1

#7403 DHFPROD-9608: Run flow in the order of the steps
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/FlowControllerTest.java
Labels: 5.8.1

#7390 DHFPROD-9701: Moving linting step on pipeline
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile
  marklogic-data-hub-central/build.gradle
Labels: 5.8.1

#7386 DHFPROD-9556: Unmerge via Explore Graph View
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/entitySearch/getRecord.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/steps/matching/matchingStep.step.json
Labels: 5.8.1

#7384 DHFPROD-9533: UI Scrollbar Improvements
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
Labels: 5.8.1

#7391 DHFPROD-7915: User menu should disappear when you click away - user avatar
  marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
  marklogic-data-hub-central/ui/src/components/header/header.tsx
Labels: 5.8.1

#7411 DHFPROD-9675: Protect against empty string collections
  examples/smart-mastering-complete/steps/merging/merge-persons.step.json
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
Labels: DO_NOT_RUN_UI_TESTS

#7417 DEVO-688: Updating Product notice for ml11
  NOTICE.txt
Labels: 5.8.1

#7419 DHFPROD-9719: Fix intermittent failures on PRs
  marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
Labels: 5.8.1

#7410 DHFPROD-9669: Cut long names in the relationship between entities and…
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
Labels: 5.8.1

#7422 DHFPROD-9638: BE - Relationships are missing on the graph
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/TDEWithRelatedInsideStructured.sjs
Labels: 5.8.1

#7412 DHFPROD-9520: Adding a relationship without foreign key defined by string as default
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Labels: 5.8.1

#7427 DHFPROD-9675: Protect against empty string collections
  examples/smart-mastering-complete/steps/merging/merge-persons.step.json
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
Labels: 5.8.1

#7415 DHFPROD-9209: Double Metaphone Fuzzy Matching
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/types/curation-types.ts
Labels: 6.0.0

#7407 DHFPROD-9558: Include/Exclude unmerged documents from future match
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/unMerge.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
Labels: 5.8.1

#7434 DHFPROD-9490: Error messages not shown
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/flow-utils.sjs
Labels: 5.8.1

#7435 DHFPROD-9679: Add error messaging for role conflict
  marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClientConfig.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CheckSecurityConfiguration.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/CheckSecurityConfigurationTest.java
Labels: 5.8.1

#7428 DHFPROD-9707: Display Values To Ignore Menu
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Labels: 6.0.0

#7437 DHFPROD-9512: Fix provenance core test failure - Intermittent
  marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
Labels: 5.8.1
