Repository marklogic/marklogic-data-hub, pull requests merged in 2022-10, with the labels that each got.

#7264 DHFPROD-9509: Update code owners file
  CODEOWNERS
Labels: DO_NOT_RUN_UI_TESTS

#7258 DHFPROD-9283: e2eFixes
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/custom.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
Labels: Needs E2E review

#7269 DHFPROD-9475: Creating HubClientConfig object during authentication
  marklogic-data-hub-api/src/main/java/com/marklogic/hub/HubClient.java
  marklogic-data-hub-api/src/main/java/com/marklogic/hub/impl/HubClientImpl.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HttpSessionHubClientProvider.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/HubClientProvider.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/auth/AuthenticationFilter.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/BaseController.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java
Labels: rc3

#7260 DHFPROD-9502: Fix Intermittent failures e2e failure on PR's
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/matching.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/entitiesSidepanel.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/entitiesSidebar.tsx
Labels: Needs E2E review

#7275 DHFPROD-9384: Update match step conversion account for more settings
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs
Labels: DO_NOT_RUN_UI_TESTS

#7270 DHFPROD-9350: e2eLinuxFixes
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/defaultIngestionListView.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
Labels: Needs E2E review

#7276 DHFPROD-9120: Triples generated for null values
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithConceptType.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithRelatedEntityType.sjs
Labels: DO_NOT_RUN_UI_TESTS

#7277 DHFPROD-9489: Fixes Win10 Chrome
  marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
Labels: Needs E2E review

#7295 DHFPROD-9588: Return concept class name
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
Labels: DO_NOT_RUN_UI_TESTS

#7296 DHFPROD-9590: Accomodate ML 11 Server Version number changes
  marklogic-data-hub-api/src/main/java/com/marklogic/hub/MarkLogicVersion.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/MarkLogicVersionTest.java
Labels: DO_NOT_RUN_UI_TESTS

#7285 DHFPROD-9356: In Explore, when toggling "Concepts" off/on the results count doesn't update.
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/graphExplore.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
Labels: Needs E2E review

#7286 DHFPROD-9416: Fixing graph in modeling when properties include -
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
  marklogic-data-hub-central/ui/e2e/cypress/support/components/common/confirmation-modal.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/property-table.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/index.d.ts
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/types/modeling-types.ts
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/properties-tab/properties-tab.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Labels: Needs E2E review

#7298 DHFPROD-9512: Added error log to get more information about this core…
  marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
Labels: DO_NOT_RUN_UI_TESTS

#7299 DHFPROD-9154: Fix SLED prefixes to be consistent
  examples/SLED/README.md
  examples/SLED/steps/mapping/HarmonizeClaimItems.step.json
  examples/SLED/steps/mapping/HarmonizeClaims.step.json
  examples/SLED/steps/mapping/mapCMSProvider.step.json
  examples/SLED/steps/mapping/mapCuram.step.json
  examples/SLED/steps/mapping/mapHospitalAffiliation1.step.json
  examples/SLED/steps/mapping/mapHospitalAffiliation2.step.json
  examples/SLED/steps/mapping/mapHospitalAffiliation3.step.json
  examples/SLED/steps/mapping/mapHospitalAffiliation4.step.json
  examples/SLED/steps/mapping/mapHospitalAffiliation5.step.json
  examples/SLED/steps/mapping/mapMMIS.step.json
  examples/SLED/steps/mapping/mapMMISNew.step.json
  examples/SLED/steps/mapping/mapOrgAssociation.step.json
  examples/SLED/steps/mapping/mapServiceLocation.step.json
Labels: DO_NOT_RUN_UI_TESTS

#7290 DHFPROD-9464: Set/remove Entity collection in manual merge/unmerge
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/steps/MergingStepControllerTest.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mastering/default/lib.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/getDefaultCollections.sjs
Labels: DO_NOT_RUN_UI_TESTS

#7303 DHFPROD-9613: Fix intermittent failures on PRs
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-view.tsx
Labels: priority:high

#7287 DHFPROD-9491: BE - Creating a relationship by a property other than id
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/template-generated.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/entities/Customer.entity.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithConceptType.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-es/generateTDEWithRelatedEntityType.sjs
Labels: DO_NOT_RUN_UI_TESTS

#7300 DHFPROD-9597: Condition Concepts search on compatible ML version
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/verifyConceptsInExplore.spec.tsx
  marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/getEntitiesTypesWithRelatedConceptsTypes.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/setup.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/suite-setup.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/triples.xml
Labels: priority:high

#7317 DHFPROD-9050: Address issues with mastering performance test
  marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/JobService.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/SystemService.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/finishJob.api
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startStep.api
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMatchOptionsLib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mastering/updateMergeOptionsLib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/saveModels.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/stepDefinition/deleteStepDefinition.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/createCustomRewriters.api
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/common.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matcher.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/merging/mergeable.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entities.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mastering/updateMatchOptions.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs
Labels: DO_NOT_RUN_UI_TESTS
