Repository marklogic/marklogic-data-hub, pull requests merged in 2022-05, with the labels that each got.

#6805 DHFPROD-8804: Run Flow After Deleting Step 5.7
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx
  marklogic-data-hub-central/ui/src/components/load/load-card.tsx
  marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
  marklogic-data-hub-central/ui/src/components/load/load-list.tsx
Labels: 5.7.2

#6840 DHFPROD-8856: Handle empty sequences from merge
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
Labels: 5.7.2

#6834 DHFPROD-8680: e2eWinFailures
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphLeafNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/login/authorization.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
Labels: 5.7.2

#6846 DHFPROD-8860: Job response modal not opening on Monitor
  marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
Labels: 5.7.2

#6839 DHFPROD-8853: firefoxE2eFailure-5.7
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
Labels: 5.7.2

#6865 DHFPROD-7939: Modify Explore Settings to Change hover properties
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/entity-type-display-settings-modal.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
Labels: Needs E2E review

#6889 DHFPROD-8609: Add scoreDocument function to Matchable
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/core/models/entityModel.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs
Labels: DO_NOT_RUN_UI_TESTS

#6902 DHFPROD-7910: Clear query should be visible even with no saved queries
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesFromManageQueries.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/crudQueriesfromExplore.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/validationsForNonHCSavedQueryUser.spec.tsx
  marklogic-data-hub-central/ui/src/components/queries/managing/edit-query-dialog/edit-query-dialog.tsx
  marklogic-data-hub-central/ui/src/components/queries/managing/manage-query-modal/manage-query.tsx
  marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx
  marklogic-data-hub-central/ui/src/components/queries/queries.tsx
  marklogic-data-hub-central/ui/src/components/queries/saving/save-queries-dropdown/save-queries-dropdown.tsx
Labels: Needs E2E review

#6915 DHFPROD-8607: Add Entity Type Display Settings to Model screen
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphSettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/entitySettings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/entity-type-display-settings-modal.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view-side-panel.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/home.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/types/base-entity-types.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/tiles/tiles.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Labels: Needs E2E review
