Repository marklogic/marklogic-data-hub, pull requests merged in 2022-04, with the labels that each got.

#6685 DHFPROD-7564: Display and Modify Entity Version Number
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/api/modeling.ts
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.module.scss
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createDraftModel.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateDraftModelInfo.sjs
Labels: 5.7.2

#6681 DHFPROD-8649: Default batch size for merge step 1
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
  marklogic-data-hub-central/ui/src/components/steps/steps.test.tsx
  marklogic-data-hub-central/ui/src/config/steps.config.ts
Labels: 5.7.2

#6694 DHFPROD-8695: updating version to 5.7-snapshot for testing
  examples/README.md
  examples/SLED/build.gradle
  examples/dh-5-example/build.gradle
  examples/dhf5-custom-hook/build.gradle
  examples/insurance/build.gradle
  examples/mapping-example/build.gradle
  examples/patient-hub/build.gradle
  examples/reference-entity-model/build.gradle
  examples/smart-mastering-complete/build.gradle
  examples/snapshot-testing/build.gradle
  examples/step-interceptors/build.gradle
  gradle.properties
  marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
  marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
  marklogic-data-hub/src/main/resources/scaffolding/build_gradle
  performance-tests/projects/commoncrawl/build.gradle
Labels: 5.7.1

#6668 DHFPROD-8614: FlowSettingsMenuEnhancements
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/pages/Run.test.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
Labels: 5.7.2

#6646 DHFPROD-8668: Irregular vis-network stabilization in Model graph view
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
  marklogic-data-hub-central/ui/src/util/modeling-utils.tsx
Labels: 5.7.2

#6693 DHFPROD-8690: Update Spring dependencies
  marklogic-data-hub-api/build.gradle
  marklogic-data-hub-central/gradle.properties
  marklogic-data-hub-junit5/build.gradle
  marklogic-data-hub/build.gradle
  ml-data-hub-plugin/build.gradle
Labels: 5.7.1

#6692 DHFPROD-8578: BE: Job Canceling
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/CancelJobsTest.java
Labels: DO_NOT_RUN_UI_TESTS, 5.7.2

#6690 DHFPROD-8690: Update Spring dependencies
  marklogic-data-hub-api/build.gradle
  marklogic-data-hub-central/gradle.properties
  marklogic-data-hub-junit5/build.gradle
  marklogic-data-hub/build.gradle
  ml-data-hub-plugin/build.gradle
Labels: 5.7.2

#6684 DHFPROD-8578: BE: Job Canceling
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/CancelJobsTest.java
Labels: DO_NOT_RUN_UI_TESTS

#6706 DHFPROD-8690: Bump ml-gradle/ml-app-deployer versions
  marklogic-data-hub-api/build.gradle
  marklogic-data-hub/build.gradle
  ml-data-hub-plugin/build.gradle
Labels: DO_NOT_RUN_UI_TESTS, 5.7.1

#6711 DHFPROD-8690: Bump ml-gradle/ml-app-deployer versions
  marklogic-data-hub-api/build.gradle
  marklogic-data-hub/build.gradle
  ml-data-hub-plugin/build.gradle
Labels: DO_NOT_RUN_UI_TESTS, 5.7.2

#6710 DHFPROD-8690: Bump ml-gradle/ml-app-deployer versions
  marklogic-data-hub-api/build.gradle
  marklogic-data-hub/build.gradle
  ml-data-hub-plugin/build.gradle
Labels: DO_NOT_RUN_UI_TESTS

#6708 DHFPROD-8591: Add filterQuery to Matchable
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/docA.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/content/tripleToBlockMatch.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/test-data/matchableInterceptors.sjs
Labels: DO_NOT_RUN_UI_TESTS

#6677 DHFPROD-8619: Apply Entity Icons to Modeling Graph View
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/config/modeling.config.ts
Labels: 5.7.2

#6701 DHFPROD-7723: ChangesMonitoringScreen
  marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/monitor.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.scss
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.scss
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
  marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.test.tsx
  marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx
  marklogic-data-hub-central/ui/src/config/tiles.config.ts
Labels: 5.7.2

#6714 DHFPROD-8620: Don't drop false boolean from JSON merges
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge2.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge3.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge1.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge2.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge3.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/Customer.entity.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/NamespacedCustomer.entity.json
Labels: 5.7.2

#6713 DHFPROD-8620: Don't drop false boolean from JSON merges
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge1.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge2.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge3.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge1.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge2.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge3.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/Customer.entity.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/entities/NamespacedCustomer.entity.json
Labels: DO_NOT_RUN_UI_TESTS

#6704 DHFPROD-7477: Add explore data links from Run flow modal
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mappingWithCustomHeader.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/relatedEntityMapping.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/load/ingestionForAllFiletypes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/reorderSteps.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonOtherValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/jsonTableViewValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/components/flows/new-flow-dialog/new-flow-dialog.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
  marklogic-data-hub-central/ui/src/pages/Run.test.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/util/search-context.tsx
Labels: 5.7.2

#6716 DHFPROD-8689: Pagination changes in search results in Explorer
  marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.module.scss
  marklogic-data-hub-central/ui/src/components/search-pagination/search-pagination.tsx
Labels: 5.7.2

#6729 DHFPROD-8686: Set Flow Status Modal Timeout
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
Labels: 5.7.2

#6738 DHFPROD-8650: Fix default merge strategy information being dropped
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/options.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/standard.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/entityDrivenMerges.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/CustMatchMerge3.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/NsCustMatchMerge3.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/customerMatchSummary.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/content/namespacedCustomerMatchSummary.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/merging/mergeCustomers.step.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/entity-driven/test-data/steps/merging/mergeNamespacedCustomers.step.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/smart-mastering/merging/merging-function-arguments.xqy
Labels: 5.7.2

#6746 DHFPROD-8761: Replace moment js with dayjs in HC
  marklogic-data-hub-central/ui/package.json
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/common.data.ts
  marklogic-data-hub-central/ui/src/components/common/hc-datetime-picker/hc-datetime-picker.tsx
  marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx
  marklogic-data-hub-central/ui/src/components/date-time-facet/date-time-facet.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.test.tsx
  marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx
  marklogic-data-hub-central/ui/src/components/load/load-list.test.tsx
  marklogic-data-hub-central/ui/src/components/load/load-list.tsx
  marklogic-data-hub-central/ui/src/components/monitor-sidebar/monitor-sidebar.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx
  marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
  marklogic-data-hub-central/ui/src/pages/Detail.tsx
  marklogic-data-hub-central/ui/src/pages/Load.test.tsx
  marklogic-data-hub-central/ui/src/util/date-conversion.tsx
Labels: 5.7.2

#6748 DHFPROD-8756: Unit Test Failures on Develop pt. 2
  marklogic-data-hub-central/ui/src/pages/Run.test.tsx
Labels: 5.7.2

#6731 DHFPROD-8557: Default views for first-time user experience when no data in FINAL
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
  marklogic-data-hub-central/ui/src/util/search-context.tsx
Labels: 5.7.2

#6747 DHFPROD-8576: Update message when clearing user data
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/environment/EnvironmentControllerTest.java
  marklogic-data-hub-central/ui/src/components/header/system-info.module.scss
  marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx
  marklogic-data-hub-central/ui/src/components/header/system-info.tsx
  marklogic-data-hub-central/ui/src/config/messages.config.tsx
  marklogic-data-hub-central/ui/src/config/steps.config.ts
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/system/getVersions.sjs
Labels: 5.7.2

#6757 DHFPROD-8768: Date range picker calendar breaks after clearing in explore tile
  marklogic-data-hub-central/ui/src/components/common/hc-datetime-picker/hc-datetime-picker.tsx
Labels: 5.7.2

#6763 DHFPROD-8712: Expose All Steps in Status Modal
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
  marklogic-data-hub-central/ui/src/pages/Run.test.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/types/run-types.ts
Labels: 5.7.2

#6765 DHFPROD-8478: Fix table update for multi-match rules
  marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
Labels: 5.7.2

#6778 DHFPROD-8788: Expose Step Running Name and Type in Response
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/job/startStep.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/setup.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/verifyStepNameAndType.sjs
Labels: 5.7.2

#6769 DHFPROD-8694: Some icons don't show when are selected in the entity type properties
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/reader.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario1.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
  marklogic-data-hub-central/ui/package-lock.json
  marklogic-data-hub-central/ui/package.json
  marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.module.scss
  marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.test.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.tsx
  marklogic-data-hub-central/ui/src/components/common/index.ts
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.tsx
Labels: 5.7.2

#6776 DHFPROD-8554: Base Entity with Wrong Title Display but Unselectable
  marklogic-data-hub-central/ui/src/components/base-entities-facet/base-entities-facet.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.test.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-specific-sidebar/entity-specific-sidebar.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/util/data-conversion.tsx
Labels: 5.7.2

#6770 DHFPROD-8710: Save Step Settings 5.7
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/services/user-preferences.tsx
Labels: 5.7.2

#6772 DHFPROD-8791: make value optional for hubFlowRunner
  marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java
Labels: DO_NOT_RUN_UI_TESTS

#6771 DHFPROD-8791: make value optional for hubFlowRunner
  marklogic-data-hub/src/main/resources/ml-modules/services/hubFlowRunner.sjs
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/RunCustomStepTest.java
Labels: DO_NOT_RUN_UI_TESTS, 5.7.2

#6785 DHFPROD-8794: StepSettingsDropdownIssue_5.7
  marklogic-data-hub-central/ui/src/components/common/hc-checkbox/hc-checkbox.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Labels: 5.7.2

#6781 DHFPROD-7578: Stop a running step/flow from Hub Central
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/FlowController.java
  marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/theme/HCVariables.scss
  marklogic-data-hub-central/ui/src/util/run-utils.tsx
Labels: 5.7.2

#6802 DHFPROD-8800: Test Failure: verifyStepNameAndType.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/verifyStepNameAndType.sjs
Labels: DO_NOT_RUN_UI_TESTS

#6803 DHFPROD-8800: Test Failure: verifyStepNameAndType.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/step/startStep/verifyStepNameAndType.sjs
Labels: DO_NOT_RUN_UI_TESTS

#6808 DHFPROD-8771: Fix minimist security vulnerability found on palamida scan
  marklogic-data-hub-central/ui/package-lock.json
  marklogic-data-hub-central/ui/package.json
Labels: 5.7.2

#6800 DHFPROD-8617: Update Status Icons
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.module.scss
  marklogic-data-hub-central/ui/src/components/flows/flows.tsx
  marklogic-data-hub-central/ui/src/components/header/system-info.test.tsx
  marklogic-data-hub-central/ui/src/components/header/system-info.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.module.scss
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.module.scss
  marklogic-data-hub-central/ui/src/components/job-results-table-view/job-results-table-view.tsx
  marklogic-data-hub-central/ui/src/components/load/load-card.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/monitor-facet/monitor-facet.tsx
  marklogic-data-hub-central/ui/src/config/messages.config.tsx
  marklogic-data-hub-central/ui/src/config/monitoring.config.js
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/theme/HCVariables.scss
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/job/testFindStepResponses.sjs
Labels: 5.7.2

#6817 DHFPROD-8819: Running and Stopping Flow shows 'completed' status when…
  marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/flows.data.ts
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
Labels: 5.7.2

#6821 DHFPROD-8834: Fix for the scroll within entity icon sidebar in explore
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.module.scss
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.tsx
Labels: 5.7.2

#6827 DHFPROD-8812: Merge Details Timeline Error
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
Labels: 5.7.2

#6819 DHFPROD-8815: ranByStep missing in FINAL DB
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FinalDatabaseXmlFileUpgrader.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeFinalDatabaseXmlFileTest.java
Labels: 5.7.2

#6825 DHFPROD-8813: Modeling Graph Entity Physics
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
Labels: 5.7.2
