Repository marklogic/marklogic-data-hub, pull requests merged in 2022-12, with the labels that each got.

#7438 DHFPROD-9524: Option to remove collections from a document in a merge step through UI
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/mergeWarnings.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/merging.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/merging/advanced-settings.tsx
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.module.scss
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx
  marklogic-data-hub-central/ui/src/components/steps/steps.tsx
Labels: 5.8.1

#7454 DHFPROD-9616: Add call to action when a flow doesn't have any steps
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.test.tsx
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
Labels: 5.8.1

#7470 DHFPROD-9512: Fix provenance core test failure - Intermittent
  marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
Labels: DO_NOT_RUN_UI_TESTS, 5.8.1

#7458 DHFPROD-9677: Create Edit New List In Values To Ignore
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matching.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
  marklogic-data-hub-central/ui/src/theme/HCVariables.scss
Labels: 6.0.0

#7474 DHFPROD-9728: Cut long relationship names in Related Concept Classes
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
  marklogic-data-hub-central/ui/src/util/data-conversion.tsx
Labels: 5.8.1

#7464 DHFPROD-9340: Add query hashes to match summaries
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/matchable.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/mastering/matching/queryHasher.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/matching/matchableTest.sjs
Labels: DO_NOT_RUN_UI_TESTS, 6.0.0

#7481 DHFPROD-9746: Fix add merge step to flow cypress test
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/curate/addMergeStepToFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
Labels: 5.8.1

#7475 DHFPROD-9162: Patch for intermittent test failure queryStep
  marklogic-data-hub/src/test/java/com/marklogic/hub/flow/FixCreatedByStepTest.java
Labels: 5.8.1

#7484 DHFPROD-9694: Setting CYPRESS_RUN_BINARY environment var
  Jenkinsfile
Labels: DO_NOT_RUN_UI_TESTS

#7501 DEVO-699: Using nexus to download artifacts
  marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
Labels: DO_NOT_RUN_UI_TESTS

#7497 DHFPROD-9747: SLED Member's mapping step keeps loading
  examples/SLED/entities/Appointment.entity.json
  examples/SLED/entities/MedicalEquipment.entity.json
  examples/SLED/entities/OverTimeAssignment.entity.json
  examples/SLED/src/main/ml-config/entities.layout.json
Labels: 5.8.1

#7502 DEVO-699: Using nexus to download artifacts
  marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
Labels: DO_NOT_RUN_UI_TESTS

#7506 DHFPROD-9661: Relationships with structured props missing from the model
  marklogic-data-hub-central/ui/e2e/cypress/fixtures/config/hubCentral.json
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/verifyConceptClassesInModeling.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenarioModeling.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/commands.js
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/entity-type-table.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/model/graph-view.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
Labels: 5.8.1

#7483 DHFPROD-9739: Buttons with wrong position
  marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.module.scss
Labels: 5.8.1

#7485 DHFPROD-9736: Fix Git Security Vulnerabilities In Package LockJson - Group 1 and 2
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js
  marklogic-data-hub-central/ui/src/assets/mock-data/explore/search-context-mock.js
  marklogic-data-hub-central/ui/src/assets/mock-data/modeling/modeling-context-mock.ts
  marklogic-data-hub-central/ui/src/components/common/hc-input/hc-input.tsx
  marklogic-data-hub-central/ui/src/components/explore/entity-icons-sidebar/entity-icons-sidebar.test.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-explore-side-panel/graph-explore-side-panel.test.tsx
  marklogic-data-hub-central/ui/src/components/explore/table-view-group-nodes/table-view-group-nodes.test.tsx
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
  marklogic-data-hub-central/ui/src/components/footer/footer.test.tsx
  marklogic-data-hub-central/ui/src/components/header/header.test.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/modal-status/modal-status.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/properties-tab/properties-tab.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/structured-type-modal/structured-type-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/pop-over-search/pop-over-search.test.tsx
  marklogic-data-hub-central/ui/src/components/queries/queries.test.tsx
  marklogic-data-hub-central/ui/src/components/queries/saving/edit-save-query/save-changes-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/queries/saving/save-query-modal/save-query-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx
  marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
  marklogic-data-hub-central/ui/src/components/tiles/tiles.test.tsx
  marklogic-data-hub-central/ui/src/pages/Curate.test.tsx
  marklogic-data-hub-central/ui/src/pages/Load.test.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx
  marklogic-data-hub-central/ui/src/pages/Monitor.test.tsx
  marklogic-data-hub-central/ui/src/pages/TilesView.test.tsx
  marklogic-data-hub-central/ui/src/types/modeling-types.ts
  marklogic-data-hub-central/ui/src/util/uiTestCommonInterface.tsx
  marklogic-data-hub-central/ui/tsconfig.json
Labels: 6.0.0

#7493 DHFPROD-9776: Wrong behavior on selecting all Concepts after search
  marklogic-data-hub-central/ui/e2e/cypress/integration/explore/graphGroupNodes.spec.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/explore/graph-explore-side-panel.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Labels: 5.8.1

#7500 DHFPROD-9655: Do not show archived items in graph
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: 5.8.1

#7509 DHFPROD-9619: Migrate to RTL - misc
  marklogic-data-hub-central/ui/package-lock.json
  marklogic-data-hub-central/ui/package.json
  marklogic-data-hub-central/ui/src/components/detail-header/detail-header.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/footer/footer.test.tsx
  marklogic-data-hub-central/ui/src/components/json-view/json-view.test.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
  marklogic-data-hub-central/ui/src/pages/Login.test.tsx
  marklogic-data-hub-central/ui/src/setupTests.ts
Labels: 6.0.0

#7511 DHFPROD-9738: Buttons in modal out of the screen
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss
  marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.module.scss
Labels: 6.0.0

#7515 DHFPROD-9738: Buttons in modal out of the screen
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.module.scss
  marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.module.scss
Labels: 5.8.1

#7479 DHFPROD-9697: Surface invalid model messages in mlLoadModules
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger-lib.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
  marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java
  marklogic-data-hub/src/test/resources/invalid/entities/testModel.entity.json
Labels: 6.0.0

#7480 DHFPROD-9697: Surface invalid model messages in mlLoadModules
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/4/triggers/entity-model-validate-trigger-lib.xqy
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
  marklogic-data-hub/src/test/java/com/marklogic/hub/entity/EntityManagerTest.java
  marklogic-data-hub/src/test/resources/invalid/entities/testModel.entity.json
Labels: 5.8.1

#7503 DHFPROD-7296: Home Page: Links not Keyboard Accessible
  marklogic-data-hub-central/ui/src/pages/Overview.test.tsx
  marklogic-data-hub-central/ui/src/pages/Overview.tsx
Labels: 6.0.0

#7512 DHFPROD-9773: Fix Git Security Vulnerabilities Group 3
  marklogic-data-hub-central/ui/src/assets/mock-data/curation/curation-context-mock.js
  marklogic-data-hub-central/ui/src/components/entities/custom/custom-card.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-card.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/explore/data-model-display-settings-modal/data-model-display-settings-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/load/load-card.test.tsx
  marklogic-data-hub-central/ui/src/components/numeric-facet/numeric-facet.test.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx
Labels: 6.0.0

#7520 DHFPROD-9737: Fix Git Security Vulnerabilities in E2E
  marklogic-data-hub-central/ui/e2e/package-lock.json
  marklogic-data-hub-central/ui/e2e/package.json
Labels: 5.8.1

#7494 DHFPROD-8360: Add Lag to All Tooltips
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-tooltip/hc-tooltip.test.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-tooltip/hc-tooltip.tsx
  marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.test.tsx
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.test.tsx
  marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
  marklogic-data-hub-central/ui/src/components/header/system-info/system-info.test.tsx
  marklogic-data-hub-central/ui/src/components/job-response/job-response.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/components/related-entities-facet/related-entities-facet.test.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.test.tsx
  marklogic-data-hub-central/ui/src/util/common-utils.tsx
Labels: 6.0.0

#7517 DHFPROD-9708: Error Validation For Create New List
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
Labels: 6.0.0

#7525 DHFPROD-9592: Fix default label in expore graph
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: 6.0.0

#7526 DHFPROD-9592: Fix default label in expore graph
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: 5.8.1

#7533 DHFPROD-8647: Source documents navigation buttons are misplaced
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.module.scss
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/source-navigation/source-navigation.module.scss
Labels: 6.0.0
