Repository marklogic/marklogic-data-hub, pull requests merged in 2022-01, with the labels that each got.

#6407 DHFPROD-8228: Make Hub Central Documentation Links Dynamic
  marklogic-data-hub-central/ui/src/components/header/header.tsx
  marklogic-data-hub-central/ui/src/config/overview.config.ts
  marklogic-data-hub-central/ui/src/pages/Overview.test.tsx
  marklogic-data-hub-central/ui/src/pages/Overview.tsx
  marklogic-data-hub-central/ui/src/pages/TilesView.tsx
  marklogic-data-hub-central/ui/src/util/environment.tsx
Labels: 5.6.2

#6411 DHFPROD-8248: Modules loader encodes files paths at wrong moment
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommandTest.java
Labels: DO_NOT_RUN_UI_TESTS

#6415 DHFPROD-8248: Modules loader encodes files paths at wrong moment
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommandTest.java
Labels: DO_NOT_RUN_UI_TESTS, 5.6.2

#6419 DHFPROD-8254: No edit Modal appears for newly created Ruleset items i…
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
Labels: 5.6.2

#6427 DEVO-350: add publishing task to installer-for-dhs module
  installer-for-dhs/build.gradle
Labels: DO_NOT_RUN_UI_TESTS

#6428 DEVO-350: add publishing task to installer-for-dhs module
  installer-for-dhs/build.gradle
Labels: DO_NOT_RUN_UI_TESTS, 5.6.2

#6433 DHFPROD-8145: Update mapping namespaces on save
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.tsx
Labels: 5.6.2

#6441 DHFPROD-8317: Added release notes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: DO_NOT_RUN_UI_TESTS, 5.6.2

#6442 DHFPROD-8317: Added release notes and updating notices
  .github/PULL_REQUEST_TEMPLATE.md
  NOTICE.txt
Labels: DO_NOT_RUN_UI_TESTS

#6445 DHFPROD-8355: Updating the version to 5.6.2
  examples/README.md
  examples/dh-5-example/build.gradle
  examples/dhf5-custom-hook/build.gradle
  examples/insurance/build.gradle
  examples/mapping-example/build.gradle
  examples/patient-hub/build.gradle
  examples/reference-entity-model/build.gradle
  examples/smart-mastering-complete/build.gradle
  examples/snapshot-testing/build.gradle
  examples/step-interceptors/build.gradle
  gradle.properties
  marklogic-data-hub-central/ui/e2e/hc-qa-project/build.gradle
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/VersionInfo.java
  marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/data-hub-admin.json
  marklogic-data-hub/src/main/resources/scaffolding/build_gradle
  performance-tests/projects/commoncrawl/build.gradle
Labels: DO_NOT_RUN_UI_TESTS
