Repository marklogic/marklogic-data-hub, pull requests merged in 2023-03, with the labels that each got.

#7683 DHFPROD-9960: Structured Property Relationships cannot be edited
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-table/property-table.tsx
Labels: 5.8.1

#7689 DHFPROD-9941: Merge Notifications Table Alignment
  marklogic-data-hub-central/ui/src/assets/mock-data/notification-context-mock.ts
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.module.scss
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
  marklogic-data-hub-central/ui/src/util/AddTooltipWhenTextOverflow.tsx
Labels: 5.8.1

#7705 DHFPROD-9934: Running Flows After Rearrange Doesnt Work Well 5.8
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/types/run-types.ts
Labels: 5.8.1

#7697 DHFPROD-9934: Running Flows After Rearrange Doesnt Work Well
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
  marklogic-data-hub-central/ui/src/types/run-types.ts
Labels: 6.0.0

#7718 DHFPROD-10012: Stopping hubcentral service before running tests
  Jenkinsfile
Labels: DO_NOT_RUN_UI_TESTS

#7724 DHFPROD-9992: Show 4.x Trace library deprecation message in the UI
  marklogic-data-hub/src/trace-ui/src/app/header/header.component.html
  marklogic-data-hub/src/trace-ui/src/app/header/header.component.scss
  marklogic-data-hub/src/trace-ui/src/assets/img/triangle-exclamation-solid.svg
Labels: 5.8.1

#7742 DHFPROD-9767: Replace all value generated key refs with expression
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphEntitiesSettings.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphLeafNodes.cy.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/entitiesWithConceptsTypes.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/graph/searchNodes.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/entity-lib.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-entities.xqy
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/getEntitiesTypesWithRelatedConceptsTypes.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchFacets.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/nodeExpand.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/test-data/entities/Purchase.entity.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/testSchemaGeneration.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/impl/hub-entities/tdeContext/verifyTdeContext.xqy
Labels: DO_NOT_RUN_UI_TESTS, 6.0.0

#7762 DEVO-766: Copying the logs from container
  Jenkinsfile
Labels: DO_NOT_RUN_UI_TESTS, 5.8.1
