Repository marklogic/marklogic-data-hub, pull requests merged in 2023-02, with the labels that each got.

#7596 DHFPROD-9884: Undefine value after unmerging document
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/unMerge.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreUnmerge.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
  marklogic-data-hub-central/ui/src/theme/HCUtils.scss
Labels: 5.8.1

#7600 DHFPROD-8388: Accesing Forms Using Keyboard In Model Tile
  marklogic-data-hub-central/ui/src/components/common/entity-type-color-picker/entity-type-color-picker.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-icon-picker/hc-icon-picker.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.module.scss
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
  marklogic-data-hub-central/ui/src/components/modeling/property-modal/property-modal.tsx
Labels: 6.0.0

#7597 DHFPROD-9853: Facet Selection is not retaining selection
  marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx
  marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
  marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx
  marklogic-data-hub-central/ui/src/util/uiTestCommonInterface.tsx
Labels: 5.8.1

#7598 DHFPROD-9853: Facet Selection is not retaining selection
  marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.test.tsx
  marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
  marklogic-data-hub-central/ui/src/components/sidebar-footer/sidebar-footer.tsx
Labels: 6.0.0

#7584 DHFPROD-9839: Add Spinner to Curate Tile
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/addCustomStepToFlow.cy.tsx
  marklogic-data-hub-central/ui/src/components/entities/entity-tiles.module.scss
  marklogic-data-hub-central/ui/src/components/entities/entity-tiles.tsx
  marklogic-data-hub-central/ui/src/pages/Curate.test.tsx
  marklogic-data-hub-central/ui/src/pages/Curate.tsx
Labels: 6.0.0

#7608 DHFPROD-9848: Stop Flow Button Disappears After One Second
  marklogic-data-hub-central/ui/src/components/flows/flow-panel/flowPanel.tsx
  marklogic-data-hub-central/ui/src/pages/Run.tsx
Labels: 6.0.0

#7611 DHFPROD-9898: Increase timeout on 10.0.9
  Jenkinsfile
Labels: 5.8.1

#7604 DHFPROD-9840: Disable Merge Icons with Missing Permissions
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeUnmergePrivileges.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreUnmerge.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.module.scss
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx
  marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Labels: 6.0.0

#7605 DHFPROD-9840: Disable Merge Icons with Missing Permissions
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeUnmergePrivileges.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreUnmerge.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/package-lock.json
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.module.scss
  marklogic-data-hub-central/ui/src/components/explore/graph-vis-explore/graph-vis-explore.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/header/notification-modal/notification-modal.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.test.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub-central/ui/src/components/search-result/search-result.test.tsx
  marklogic-data-hub-central/ui/src/components/search-result/search-result.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.test.tsx
  marklogic-data-hub-central/ui/src/components/table-view/table-view.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
Labels: 5.8.1

#7617 DHFPROD-9813: Core test failure Provenance - Get more info
  marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/entitySearch/GetRecordTest.java
  marklogic-data-hub/src/test/resources/test-projects/provenance-test/flows/inline.flow.json
Labels: 5.8.1

#7618 DHFPROD-7310: Merge: Keyboard Accessibility
  marklogic-data-hub-central/ui/src/components/common/hc-table/hc-table.tsx
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.module.scss
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merge-strategy-dialog/merge-strategy-dialog.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-step-detail/merging-step-detail.tsx
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
Labels: 6.0.0

#7626 DHFPROD-9919: Add ML 11.0.0 to nightly build
  Jenkinsfile
Labels: 5.8.1

#7625 DHFPROD-9842: Make Explore Stabilization Message Dismissable
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/viewNavigation.cy.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-alert/hc-alert.module.scss
  marklogic-data-hub-central/ui/src/components/common/hc-alert/hc-alert.tsx
  marklogic-data-hub-central/ui/src/components/explore/graph-view-explore/graph-view-explore.tsx
  marklogic-data-hub-central/ui/src/services/user-preferences.tsx
Labels: 6.0.0

#7622 DHFPROD-9899: Possible Combinations of Matched Rulesets container wont expand
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
Labels: 5.8.1

#7630 DHFPROD-9767: Add limit to SPARQL query to reduce memory consumption
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: 6.0.0

#7639 DHFPROD-9866: Merge step is failing when tripleMerge is defined in th…
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
Labels: DO_NOT_RUN_UI_TESTS, 5.8.1

#7636 DHFPROD-9878: Boolean Property Results Missing in Explore Table
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/entities/entity-search-lib.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addDocumentMetadataToSearchResults.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/addPropertiesToSearchResponse.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/jane.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.json
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/content/sally.xml
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/entities/search/test-data/entities/Customer.entity.json
Labels: 5.8.1

#7615 DHFPROD-7309: Match Keyboard Accessibility
  marklogic-data-hub-central/ui/src/components/common/hc-select/hc-select.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-tag/hc-tag.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-multiple-modal/ruleset-multiple-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/threshold-modal/threshold-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/merging/add-merge-rule/merge-rule-dialog.test.tsx
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
Labels: 6.0.0

#7633 DHFPROD-9866: Merge step is failing when tripleMerge is defined in th…
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/mastering/merging/mergeableTest.sjs
Labels: DO_NOT_RUN_UI_TESTS, 6.0.0

#7629 DHFPROD-9767: Add limit to SPARQL query to reduce memory consumption
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
Labels: 5.8.1

#7638 DHFPROD-9938: Clear Data Boxes are shrinked
  marklogic-data-hub-central/ui/src/components/common/hc-card/hc-card.module.scss
  marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-card.module.scss
Labels: 6.0.0

#7623 DHFPROD-9899: Possible Combinations of Matched Rulesets container wont expand
  marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
Labels: 6.0.0

#7631 DHFPROD-9493: Address coverity report items
  installer-for-dhs/src/test/java/com/marklogic/hub/dhs/installer/MainTest.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandler.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/web/SslUtil.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/HubCentralTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/SessionManagerTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/DownloadRecordTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java
  marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/AbstractSparkReadTest.java
  marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/HandleFailedWriteTest.java
  marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java
  marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/ReferenceModelProject.java
  marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/TestObject.java
  marklogic-data-hub/src/main/java/com/marklogic/client/ext/file/CacheBusterDocumentFileProcessor.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/BulkUtil.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/ext/mlunittest/TestSuiteGenerator.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/HubCentralConverter.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/CommandLineFlowInputs.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FinalDatabaseXmlFileUpgrader.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MappingManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/collector/DiskQueue.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/flow/impl/LegacyFlowImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/impl/LegacyFlowManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/job/impl/LegacyJobManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/DiskQueue.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/FileUtil.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONStreamWriter.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/VerifyEndpointPrivilegesTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsPerformanceTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsTokenReplaceTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/StreamGobbler.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/tools/DataServiceGenerator.java
  marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
  ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PrintInheritableRolesTask.groovy
Labels: 5.8.1

#7632 DHFPROD-9493: Address coverity report items
  installer-for-dhs/src/test/java/com/marklogic/hub/dhs/installer/MainTest.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/EnvironmentController.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/EntitySearchManager.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/entities/search/impl/CreatedOnFacetHandler.java
  marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/web/SslUtil.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/HubCentralTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/auth/SessionManagerTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/DownloadRecordTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/entities/search/EntitySearchManagerTest.java
  marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/AbstractSparkReadTest.java
  marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/writer/HandleFailedWriteTest.java
  marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/AbstractHubClientTest.java
  marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/ReferenceModelProject.java
  marklogic-data-hub-test/src/main/java/com/marklogic/hub/test/TestObject.java
  marklogic-data-hub/src/main/java/com/marklogic/client/ext/file/CacheBusterDocumentFileProcessor.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/BulkUtil.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/CreateGranularPrivilegesCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/GenerateHubTDETemplateCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubArtifactsCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadUserModulesCommand.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/ext/mlunittest/TestSuiteGenerator.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/flow/impl/FlowRunnerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/HubCentralManager.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/hubcentral/conversion/HubCentralConverter.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/CommandLineFlowInputs.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/DataHubImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/EntityManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/FinalDatabaseXmlFileUpgrader.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/HubProjectImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MappingManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/ScaffoldingImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/StepDefinitionManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/collector/DiskQueue.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/flow/impl/LegacyFlowImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/impl/LegacyFlowManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/legacy/job/impl/LegacyJobManagerImpl.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/DiskQueue.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/FileUtil.java
  marklogic-data-hub/src/main/java/com/marklogic/hub/util/json/JSONStreamWriter.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/HubTestBase.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/VerifyEndpointPrivilegesTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsPerformanceTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/commands/LoadUserArtifactsTokenReplaceTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/hubcentral/AllArtifactsProject.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/impl/UpgradeProjectTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/master/MasterTest.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/mlcp/StreamGobbler.java
  marklogic-data-hub/src/test/java/com/marklogic/hub/tools/DataServiceGenerator.java
  marklogic-data-hub/src/testFixtures/java/com/marklogic/hub/test/AbstractHubTest.java
  ml-data-hub-plugin/src/main/groovy/com/marklogic/hub/gradle/task/PrintInheritableRolesTask.groovy
Labels: 6.0.0

#7634 DHFPROD-9928: Editing a Rs using struct props creates a new rs
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
Labels: 5.8.1

#7635 DHFPROD-9928: Editing a Rs using struct props creates a new rs
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-vis/graph-vis.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
Labels: 6.0.0

#7645 DHFPROD-9935: In Explore, the facets count positioning is off for lon…
  marklogic-data-hub-central/ui/src/components/common/hc-facet-indicator/hc-facet-indicator.test.tsx
  marklogic-data-hub-central/ui/src/components/common/hc-facet-indicator/hc-facet-indicator.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet-name.tsx
  marklogic-data-hub-central/ui/src/components/facet/facet.module.scss
Labels: 5.8.1

#7648 DHFPROD-9930: Unable to select property
  marklogic-data-hub-central/ui/package.json
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
Labels: 5.8.1

#7646 DHFPROD-9930: Unable to select property
  marklogic-data-hub-central/ui/package.json
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.module.scss
  marklogic-data-hub-central/ui/src/components/entity-property-tree-select/entity-property-tree-select.tsx
Labels: 6.0.0

#7640 DHFPROD-9922: Limit Table Width in Explore
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonTableViewValidations.cy.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub-central/ui/src/util/data-conversion.tsx
Labels: 6.0.0

#7641 DHFPROD-9922: Limit Table Width in Explore
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/jsonTableViewValidations.cy.tsx
  marklogic-data-hub-central/ui/src/components/results-tabular-view/results-tabular-view.tsx
  marklogic-data-hub-central/ui/src/util/data-conversion.tsx
Labels: 5.8.1

#7593 DHFPROD-9849: Use preview param to not write merge preview
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeNotification.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/run/runFlow.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/monitor/monitorTableValidations.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
  marklogic-data-hub/src/main/java/com/marklogic/hub/impl/MasteringManagerImpl.java
  marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs
Labels: 6.0.0

#7658 DHFPROD-9937: Fix amp test version check
  marklogic-data-hub/src/test/java/com/marklogic/hub/deploy/DeployUserAmpsTest.java
Labels: DO_NOT_RUN_UI_TESTS, 6.0.0

#7656 DHFPROD-9933: Decode URIs for graph
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer%20without%20id.json
Labels: 6.0.0

#7655 DHFPROD-9933: Decode URIs for graph
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/graph-utils.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearch.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/graphSearchWithConfigProperties.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/graph/test-data/content/customer%20without%20id.json
Labels: 5.8.1

#7642 DHFPROD-9900: Unmerge Modal Column Order
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
Labels: 6.0.0

#7660 DHFPROD-9926: Export Table Modal In Explore View Overflowed
  marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
Labels: 6.0.0

#7659 DHFPROD-9926: Export Table Modal In Explore ViewOverflowed
  marklogic-data-hub-central/ui/src/components/query-export/query-export-modal/query-export-modal.tsx
Labels: 5.8.1

#7644 DHFPROD-9900: Unmerge Modal Column Order
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.module.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
Labels: 5.8.1

#7653 DHFPROD-9936: Facet Selection is not retaining collection facet selection
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/graphSidePanel.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/src/components/sidebar/sidebar.tsx
  marklogic-data-hub-central/ui/src/pages/Browse.tsx
Labels: 5.8.1

#7661 DHFPROD-9945: Palamida readable stream
  marklogic-data-hub-central/ui/package-lock.json
  marklogic-data-hub-central/ui/package.json
Labels: 5.8.1

#7665 DHFPROD-9957: Allow entity with missing structured prop definition
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/mappable-entity-lib.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getEntitiesForMapping/test-data/entities/Order.entity.json
Labels: 6.0.0

#7669 DHFPROD-9943: Hide entity versioning
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java
  marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario1.cy.tsx
  marklogic-data-hub-central/ui/src/api/modeling.ts
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createDraftModel.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateDraftModelInfo.sjs
Labels: 5.8.1

#7667 DHFPROD-9943: Hide entity versioning
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/ModelTest.java
  marklogic-data-hub-central/src/test/java/com/marklogic/hub/central/controllers/model/PublishModelsTest.java
  marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/writerScenario1.cy.tsx
  marklogic-data-hub-central/ui/src/api/modeling.ts
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
  marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/graph-view.test.tsx
  marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.tsx
  marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
  marklogic-data-hub-central/ui/src/pages/Modeling.tsx
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/createDraftModel.sjs
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/models/updateDraftModelInfo.sjs
Labels: 6.0.0

#7664 DHFPROD-9957: Allow entity with missing structured prop definition
  marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/data-services/mapping/mappable-entity-lib.sjs
  marklogic-data-hub/src/test/ml-modules/root/test/suites/data-hub/5/data-services/mapping/getEntitiesForMapping/test-data/entities/Order.entity.json
Labels: 5.8.1

#7663 DHFPROD-9946: Multi Match Error in All Data Card View
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.scss
  marklogic-data-hub-central/ui/src/components/entities/matching/compare-values-modal/compare-values-modal.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.test.tsx
  marklogic-data-hub-central/ui/src/components/record-view/record-view.tsx
Labels: 5.8.1

#7674 DHFPROD-9939: Curate Card Footers Are Cut Off
  marklogic-data-hub-central/ui/src/components/entities/merging/merging-card.tsx
Labels: 6.0.0

#7666 DHFPROD-8389: Create/Edit Step Keyboard Navigation
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/matchWarnings.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/mergeNotification.cy.tsx
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.test.tsx
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings.tsx
  marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-target-collections.tsx
  marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.test.tsx
  marklogic-data-hub-central/ui/src/components/entities/create-edit-step/create-edit-step.tsx
Labels: 6.0.0

#7676 DHFPROD-9896: Fix intermittent failures on nightly
  Jenkinsfile
  marklogic-data-hub-central/ui/e2e/cypress/e2e/curation/curate/custom.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/explore/exploreUnmerge.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/login/authorization.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/entitySettings.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/graphValidations.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/matching-step-detail.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/curate.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/home.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/login.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/model.tsx
  marklogic-data-hub-central/ui/e2e/cypress/support/pages/run.tsx
Labels: 5.8.1
